version: '3.8'

services:
  db:
    image: postgres:11
    restart: always
    volumes:
      - ./data/postgres/dbb:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=book_admin
      - POSTGRES_HOST_AUTH_METHOD=trust
  book_store:
    build: .
    container_name: book_store
    image: book_store:book_store
    environment:
      - SECRET_KEY=django-insecure-gv78xsl=x-&_1o5v)@q7zk7mn!=^)uiw*z6)vrf53x+8&ww9kg
      - DEBUG=1
    ports:
      - 8000:8000
    volumes:  
      - .:/book_store
    depends_on:
      - db
    command: python manage.py runserver 0.0.0.0:8000
volumes:
      postgres_data: